data = LOAD '$input' USING PigStorage(',') AS (VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount);

generated = FOREACH data GENERATE payment_type;

filtered = FILTER generated BY payment_type != 'payment_type' AND payment_type != '';

grouped = GROUP filtered BY payment_type;

counted = FOREACH grouped GENERATE group, COUNT(filtered) as CNT_DATA;

ordered = ORDER counted BY CNT_DATA;

STORE ordered into '$output';
